### ISSUE TITLE
packages 

### ISSUE THREAD

**Issue by ixnp** [learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/205983?module_item_id=472696

### Concern

pytest will not run without `pytest = "x"` included in [packages] section of Pipfile OR If `pipenv installed -d` is run to assure the development packages are installed. I don’t believe this flag was covered in previous labs.

This issue persists in all of the SQLAlchemy labs. 

### Suggested Changes

Add a reminder to run `pipenv installed -d` to ensure all dependencies are installed.

**Comment by professor-ben** [comment]
This is an established issue that's a little odd because of the context we're using the tests in. The best solution for our use case- I think- is installing testing and debugging tools at all levels in the environment and avoiding dev dependencies for the time being.

With that in mind, the solution I'm going to push today is a rewrite of all the Pipfiles in the SQLAlchemy and SQLAlchemy Relationships modules on Canvas.
