### ISSUE TITLE
How is the Script Working?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-defining-schema-with-sqlalchemy#6]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/205983?module_item_id=472696

### Concern

There might be a few missing pieces in this lesson when discussing the script at the end:

Will the script still be called from the module that's importing `sqlalchemy_sandbox.py`? Or will adding `if __name__ = '__main__' ` simply prevent it being run from other modules at all?

Is the rest of the code in this file also going to run before any other code in a module that imports this file? 

What's the utility of making this file a script? Is that commonly done?

I can see students being confused as to why this material is included in this lesson - it's relevance it's immediately apparent.

**Comment by professor-ben** [comment]
Hey Matt,

We went back and added this to Configuring Applications earlier this month. I totally agree that this isn't the best time to introduce it.

So that you don't have to go back several modules (we hate to make anyone do that) the basic idea is that any assignment, function call (`()`) or class instantiation (also `()`, but on a class) will be run regardless of the if/name/main block. The purpose of that block is to put any scripted code in there so that anything that will be run is only run if the file itself is called from the command line. We include the declarative base instantiation regardless because it does need to be used by other modules upon import.

I'll go ahead and remove this now.

Thanks,
Ben

**Comment by Matt-Eva** [comment]
Hey Ben,

Thanks for the clarification! I'll go back and review that previous section. Thanks for the prompt reply as well!

Cheers,

Matt
